### PR TITLE
Removing HTML inline styling

### PR DESCRIPTION
**Pull request by alex-windett**

### CODE REVIEW

**Comment by alex-windett** [comment]
@ramitos I understand your example and am happy to use, but I was thinking that if we did the way it is at the moment there would be less code changed, and would act more similar to how react is out of the box

**Comment by ramitos** [comment]
@alex-windett but the issue was created specifically to remove all those style objects and convert into `styled-components`. Also, your fix wont work because you're passing an object to a function that expects a string:

```js
const buttonStyle = {
  float: 'right'
};

const Button = styled.button`
  color: red;
  {props => props.styles}
`

<Button styles={buttonStyle} />
```

in the end you get something like: 

```
color: red;
[Object object]
```

**Comment by alex-windett** [comment]
@ramitos styled-components accept objects. 

I've used it here in the frontend -https://github.com/yldio/joyent-portal/blob/master/frontend/src/components/people-list/table/tooltip.js#L57.

With the tooltip ui component https://github.com/yldio/joyent-portal/blob/master/ui/src/components/tooltip/index.js#L42

**Comment by ramitos** [comment]
@alex-windett you're right, I'm sorry! I wasn't aware of that 😐

**Comment by ramitos** [comment]
(sorry, I closed by mistake)

**Comment by alex-windett** [comment]
No Worries, will re-work components tomorrow

**Comment by alex-windett** [comment]
@juditgreskovits @ramitos updated with Sergio's comments - if you could take a look tomorrow

**Comment by ramitos** [comment]
@alex-windett good 😉 it would be great if you could convert some of the existent inline styles into extended styled components 😉

**Comment by alex-windett** [comment]
@ramitos I thought i removed all inline styles... Could you point me to some that I missed

**Comment by ramitos** [comment]
stuff like this https://github.com/yldio/joyent-portal/blob/705aa32e73a77bc5fbf64e9a47d8d7d62cb28666/frontend/src/components/people-list/index.js#L12 😉

**Comment by alex-windett** [comment]
May not have pushed latest commit - https://github.com/yldio/joyent-portal/blob/fix/inline-styles/frontend/src/components/people-list/index.js#L17

**Comment by ramitos** [comment]
Sorry, I hadn't seen that commit. Looks good 😉 but I think you missed these https://github.com/yldio/joyent-portal/blob/60fd874b3db4cd9f572fc756d2a73113f7d7e05d/frontend/src/components/people-list/invite.js#L79-L94

**Comment by alex-windett** [comment]
@ramitos  Ah yes, Updated where applicable however, line 79 it uses react-select so having to use a style object instead of styled-component format

**Comment by ramitos** [comment]
> however, line 79 it uses react-select so having to use a style object instead of styled-component format

Ah, makes sense 😉

**Pull request merged**
